# Generated by Django 5.0 on 2024-01-08 16:52

import django.core.validators
import django.db.models.deletion
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collegeadmin', '0028_staff_user_id_student_user_id'),
        ('superadmin', '0012_registercollege_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('students_ids', models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('subject_ids', models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('college_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superadmin.registercollege')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collegeadmin.department')),
            ],
        ),
    ]
