# Generated by Django 5.0 on 2024-01-15 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeadmin', '0028_staff_user_id_student_user_id'),
        ('staffuser', '0001_initial'),
        ('superadmin', '0012_registercollege_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='college_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='superadmin.registercollege'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='collegeadmin.department'),
        ),
    ]
