# Generated by Django 5.0 on 2024-01-15 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffuser', '0002_alter_classroom_college_id_alter_classroom_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
