# Generated by Django 5.0 on 2024-01-17 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeadmin', '0028_staff_user_id_student_user_id'),
        ('staffuser', '0004_classroomforteacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanInClassroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('attendance_status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late')], max_length=10)),
                ('class_room_staff_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staffuser.classroomforteacher')),
                ('student_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='collegeadmin.student')),
            ],
        ),
        migrations.CreateModel(
            name='ModulesForClassRoomForTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_url', models.CharField(max_length=500, null=True)),
                ('module_video_url', models.CharField(max_length=500, null=True)),
                ('class_room_staff_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staffuser.classroomforteacher')),
            ],
        ),
    ]
