# Generated by Django 5.0 on 2024-01-18 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffuser', '0005_attendaninclassroom_modulesforclassroomforteacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendaninclassroom',
            old_name='class_room_staff_id',
            new_name='class_room_for_staff_id',
        ),
    ]
