# Generated by Django 5.0.1 on 2024-02-07 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffuser', '0006_rename_class_room_staff_id_attendaninclassroom_class_room_for_staff_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='semester',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
