# Generated by Django 5.0.1 on 2024-02-07 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffuser', '0007_classroom_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='active',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
