# Generated by Django 5.0 on 2023-12-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('user_image', models.ImageField(blank=True, null=True, upload_to='profile')),
                ('age', models.IntegerField()),
                ('department', models.CharField(max_length=150)),
                ('register_no', models.IntegerField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('city', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=150)),
                ('zip_code', models.BigIntegerField()),
                ('address', models.CharField(max_length=300)),
                ('phone_number', models.CharField(max_length=20)),
                ('created', models.DateField(null=True)),
            ],
        ),
    ]
