# Generated by Django 5.0 on 2024-01-01 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeadmin', '0003_remove_collegedatabase_end_date_and_more'),
        ('superadmin', '0012_registercollege_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='collge_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='superadmin.registercollege'),
        ),
    ]
