# Generated by Django 5.0 on 2024-01-01 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collegeadmin', '0004_department_collge_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='collge_name',
            new_name='college_name',
        ),
    ]
