# Generated by Django 5.0 on 2024-01-02 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collegeadmin', '0005_rename_collge_name_department_college_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='name',
            new_name='coursename',
        ),
    ]
