# Generated by Django 5.0 on 2024-01-03 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeadmin', '0006_rename_name_department_coursename'),
        ('superadmin', '0012_registercollege_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegedatabase',
            name='collge_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='superadmin.registercollege'),
        ),
    ]
