# Generated by Django 5.0 on 2024-01-04 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeadmin', '0007_collegedatabase_collge_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegedatabase',
            name='address',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='collegedatabase',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='collegedatabase',
            name='city',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='collegedatabase',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='collegedatabase',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='collegedatabase',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='collegedatabase',
            name='state',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='collegedatabase',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='collegedatabase',
            name='zip_code',
            field=models.BigIntegerField(null=True),
        ),
    ]
