# Generated by Django 5.0 on 2024-01-04 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeadmin', '0009_remove_collegedatabase_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegedatabase',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile'),
        ),
    ]
