# Generated by Django 5.0 on 2024-01-04 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collegeadmin', '0010_collegedatabase_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collegedatabase',
            name='department',
        ),
    ]
