# Generated by Django 5.0 on 2024-01-04 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeadmin', '0011_remove_collegedatabase_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collegeadmin.staff'),
        ),
    ]
