# Generated by Django 5.0 on 2024-01-05 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeadmin', '0012_alter_subject_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='college_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='collegeadmin.collegedatabase'),
        ),
    ]
