# Generated by Django 5.0 on 2024-01-05 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeadmin', '0013_session_college_id'),
        ('superadmin', '0012_registercollege_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='college_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='superadmin.registercollege'),
        ),
    ]
