# Generated by Django 5.0 on 2024-01-05 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeadmin', '0014_alter_session_college_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='staff',
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='collegeadmin.department'),
        ),
        migrations.AddField(
            model_name='student',
            name='student',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='collegeadmin.collegedatabase'),
        ),
        migrations.AlterField(
            model_name='student',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='collegeadmin.session'),
        ),
    ]
