# Generated by Django 5.0 on 2024-01-06 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeadmin', '0015_remove_student_staff_student_course_student_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegedatabase',
            name='email',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
