# Generated by Django 5.0 on 2024-01-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeadmin', '0016_collegedatabase_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegedatabase',
            name='primary_password',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
