# Generated by Django 5.0 on 2024-01-06 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeadmin', '0017_collegedatabase_primary_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegedatabase',
            name='email_sent',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
