# Generated by Django 5.0 on 2024-01-06 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeadmin', '0021_collegedatabase_email_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegedatabase',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
