# Generated by Django 5.0 on 2024-01-06 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeadmin', '0022_alter_collegedatabase_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegedatabase',
            name='created',
            field=models.DateField(blank=True, null=True),
        ),
    ]
