# Generated by Django 5.0 on 2024-01-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeadmin', '0023_alter_collegedatabase_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='semseter',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
