# Generated by Django 5.0 on 2024-01-08 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeadmin', '0025_alter_subject_semseter'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='is_hod',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='semester',
            field=models.CharField(blank=True, null=True, max_length=30),
        ),
    ]
