# Generated by Django 5.0 on 2024-01-08 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeadmin', '0026_staff_is_hod_student_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='is_hod',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
