# Generated by Django 5.0 on 2024-01-24 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeadmin', '0028_staff_user_id_student_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestForLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reasonforleave', models.CharField(max_length=300, null=True)),
                ('from_date', models.DateField(null=True)),
                ('to_date', models.DateField(null=True)),
                ('approval_status', models.BooleanField(null=True)),
                ('requestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collegeadmin.collegedatabase')),
            ],
        ),
    ]
