# Generated by Django 5.0 on 2024-01-24 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeadmin', '0030_requestforleave_leavetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestforleave',
            name='approval_status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
