# Generated by Django 5.0.1 on 2024-02-07 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeadmin', '0031_alter_requestforleave_approval_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='active',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
