# Generated by Django 5.0.1 on 2024-02-07 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeadmin', '0032_department_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='active',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
