# Generated by Django 4.0 on 2024-02-08 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeadmin', '0034_alter_subject_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestforleave',
            name='leavetype',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
