# Generated by Django 4.0 on 2024-02-09 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeadmin', '0035_alter_requestforleave_leavetype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='is_hod',
            field=models.BooleanField(default=False),
        ),
    ]
