# Generated by Django 4.0 on 2024-02-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeadmin', '0036_alter_staff_is_hod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.CharField(default='abc', max_length=30),
            preserve_default=False,
        ),
    ]
