# Generated by Django 4.0 on 2024-02-09 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeadmin', '0041_alter_student_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.IntegerField(default=0),
        ),
    ]
