# Generated by Django 5.0 on 2024-01-26 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('collegeadmin', '0031_alter_requestforleave_approval_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collegeadmin.collegedatabase'),
        ),
    ]
