# Generated by Django 5.0.1 on 2024-02-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_blogpost_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='blog'),
        ),
    ]
