# Generated by Django 5.0 on 2023-12-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterCollege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collegename', models.CharField(max_length=60)),
                ('state', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_activate', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
    ]
