# Generated by Django 5.0 on 2023-12-24 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0003_useraccount_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_student',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='is_teacher',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
