# Generated by Django 5.0 on 2023-12-25 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0004_useraccount_is_student_useraccount_is_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='is_student',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='is_teacher',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='user_type',
            field=models.CharField(blank=True, choices=[(1, 'College_Admin'), (2, 'Staff'), (3, 'Student')], default=1, max_length=1, null=True),
        ),
    ]
