# Generated by Django 5.0 on 2023-12-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0005_remove_useraccount_is_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registercollege',
            name='Verfication_email_status',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='registercollege',
            name='details_verified',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
