# Generated by Django 5.0 on 2023-12-26 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0006_registercollege_verfication_email_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registercollege',
            name='user_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
