# Generated by Django 5.0 on 2023-12-26 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0007_registercollege_user_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='registercollege',
            name='primary_password',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
