# Generated by Django 5.0 on 2023-12-26 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0010_alter_registercollege_primary_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registercollege',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
