# Generated by Django 5.0 on 2023-12-29 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0011_alter_registercollege_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='registercollege',
            name='subscription',
            field=models.BooleanField(null=True),
        ),
    ]
