# Generated by Django 4.0 on 2024-02-08 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0013_useraccount_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='otp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
